#!/bin/bash -ex
VIDEO=$(ls /dev/video? | head -1)
SERIAL=$(ls /dev/ttyUSB? | head -1)

docker run \
  -it --rm \
  -u "$(id -u):$(id -g)" \
  -e DISPLAY="$DISPLAY" \
  -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
  --read-only \
  --device "$VIDEO" \
  --group-add "$(getent group video | cut -d: -f3)" \
  --device "$SERIAL" \
  --group-add "$(getent group dialout | cut -d: -f3)" \
  hello-human "$@"
