#!/bin/bash -ex
if [ $# -lt 2 ]
then
  echo "$0 </dev/videoX> </dev/ttyUSBY> [args for script]" >&2
fi
VIDEO=$1
SERIAL=$2
shift 2

if [ -z "$TAG" ]
then
  if ! git describe --exact-match --tags > /dev/null 2>&1
  then
    TAG="latest"
  else
    TAG=$(git describe --exact-match --tags | tr ' ' '\n' | head -1)
  fi
else
  echo "$0: TAG is already explicitly set to '$TAG' - using this one, then"
fi

[ -z "$DISPLAY" ] || xhost "+si:localuser:$USER"

docker run \
  -it --rm \
  -u "$(id -u):$(id -g)" \
  -e DISPLAY="$DISPLAY" \
  -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
  --read-only \
  --device "$VIDEO" \
  --group-add "$(getent group video | cut -d: -f3)" \
  --device "$SERIAL" \
  --group-add "$(getent group dialout | cut -d: -f3)" \
  "baszerr/hello_human:$TAG" --video "$VIDEO" --serial "$SERIAL" "$@"
